auctionsonline/auctionsonline/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('website/', include('website.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auctionsonline/website/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'website'

urlpatterns = [
	path('', views.index, name='index'),
	path('login/', views.login_page, name='login_view'),
	path('logout/', views.logout_page, name='logout_view'),
	path('register/', views.register_page, name='register_page'),
	path('register/new_user/', views.register, name='register'),
    path('Leiloes/', views.produto_list, name='Leiloes'),
    path('category/<str:category>/', views.filter_leilao, name='filter_auctions'),
    path('watchlist/<int:leilao_id>/', views.watchlist, name='watchlist'),
    path('search_leiloes/', views.search_leiloes, name='search_leiloes'),
    path('search_results/<str:date>/<str:time>/', views.search_list, name='search_results'),
    path('balance/', views.balance, name='balance'),
    path('balance/topup/', views.topup, name='topup'),
    path('watchlist/', views.watchlist_page, name='watchlist'),
    path('bid/<int:leilao_id>/', views.bid_page, name='bid_page'),
    path('bid/<int:leilao_id>/raise_bid/', views.raise_bid, name='raise_bid'),
]

auctionsonline/website/models.py
from django.contrib.auth.models import User
from django.contrib.sessions.models import Session
from django.db import models

# Create your models here.


class Users(models.Model):
	user_id = models.IntegerField(primary_key=True, serialize=True, unique=True)
	username = models.CharField(max_length=40, null=True)
	password = models.CharField(max_length=100)
	email = models.EmailField()
	p_nome = models.CharField(max_length=50)
	u_nome = models.CharField(max_length=50)
	credito = models.DecimalField(max_digits=6, decimal_places=2)
	telefone = models.CharField(max_length=14,)
	endereco = models.CharField(max_length=255)
	cidade = models.CharField(max_length=45)
	cod_postal = models.CharField(max_length=45)
	pais = models.CharField(max_length=45)
	data_registo = models.DateField()

	def __str__(self):
		user = Users.objects.get(id=self.user_id)
		return "id=" + str(self.pk) + " username=" + Users.username + " email=" + Users.email
	

class Leiloes(models.Model):
    leilao_id = models.IntegerField(primary_key= True, unique= True, serialize= True)
    numero_de_licitacoes = models.IntegerField()
    preco_base = models.FloatField()
    data_hora_inicio = models.DateTimeField()
    data_hora_fim = models.DateTimeField()
    incremento_minimo = models.FloatField(default=100.00)

    def __str__(self):
        return "ID:" + str(self.pk) 
    
class Negociacoes(models.Model):
	negociacao_id = models.IntegerField(primary_key=True, serialize=True, unique=True)
	numero_de_licitacoes = models.IntegerField()
	valor_proposto = models.FloatField()
	data_hora_inicio = models.DateTimeField()
	data_hora_fim = models.DateTimeField()

class Watchlist(models.Model):
	watchlist_id = models.IntegerField(primary_key=True, unique=True, serialize=True)
	temp_user_id = models.CharField()
	leiloes = models.ManyToManyField(Leiloes)
	negociacoes = models.ManyToManyField(Negociacoes)


class Lotes(models.Model):
	lote_id = models.IntegerField('ID', primary_key=True, serialize=True, unique=True)
	lote_nome = models.CharField(max_length=50)
	descriacao = models.TextField()
	
	def __str__(self):
		return 'LOTE ID:'+ str(self.pk) 


class Produtos(models.Model):
    CATEGORIA= (
		('LAP', 'Laptop'),
		('CON', 'Console'),
		('GAD', 'Gadget'),
		('GAM', 'Game'),
		('TEL', 'TV')
	)
    prod_id = models.IntegerField(primary_key=True, unique=True, serialize=True)
    titulo = models.CharField(max_length=255)
    lote = models.ForeignKey(Lotes, on_delete=models.PROTECT)
    leilao = models.ForeignKey(Leiloes, on_delete=models.PROTECT, null=True)
    negociacoes = models.ForeignKey(Negociacoes, on_delete=models.PROTECT, null=True)
    descricao = models.CharField(max_length=500)
    quantidade = models.IntegerField()
    category = models.CharField(
		max_length=3,
		choices=CATEGORIA
	)
    data_insercao = models.DateTimeField(auto_now_add=True, blank=True)
    def __str__(self):
        return "ID:" + str(self.pk) + " " + self.titulo

class Fotos(models.Model):
	foto_id = models.IntegerField(primary_key=True, unique=True, serialize=True)
	url= models.ImageField(upload_to=('LeilaoBD2/auctionsonline/media/images/')) 
	produto = models.ForeignKey(Produtos, on_delete=models.PROTECT)
	
	def __str__(self):
		return "USER_ID:" + str(self.user) + " PRODUTO_ID:" + str(self.produto)
	
class Licitacoes(models.Model):
	licitacao_id = models.IntegerField(primary_key=True, serialize=True, unique=True)
	user= models.ForeignKey(User, on_delete=models.CASCADE)
	leilao = models.ForeignKey(Leiloes, on_delete=models.CASCADE, null=True)
	negociacoes = models.ForeignKey(Negociacoes, on_delete=models.CASCADE, null=True)
	data_hora_licitacao = models.DateTimeField()
	valor_minimo = models.FloatField()
	valor_final = models.FloatField()
	estado = models.BooleanField(default=0)
	
	def __str__(self):
		return "USER_ID:" + str(self.user) + " LEILAO_ID:" + \
			str(self.leilao) + " " + str(self.data_hora_licitacao) 


class Faturas(models.Model):
	fatura_id = models.AutoField('Fatura ID', primary_key=True, unique=True, serialize=True)
	data_fatura  = models.DateTimeField("Data da fatura")
	licitacao = models.ForeignKey(Licitacoes, on_delete=models.CASCADE)
 

auctionsonline/website/forms.py
from django import forms
from website.models import Users

class RegistrationForm(forms.Form):
    username = forms.CharField(max_length=45)
    password1 = forms.CharField(max_length=100)
    password2 = forms.CharField(max_length=100)
    email = forms.EmailField()
    p_nome = forms.CharField(max_length=50)
    u_nome = forms.CharField(max_length=50)
    credito = forms.FloatField()
    telefone = forms.CharField(max_length=14)
    endereco = forms.CharField(max_length=255)
    cidade = forms.CharField(max_length=45)
    cod_postal = forms.CharField(max_length=45)
    pais = forms.CharField(max_length=45)
    data_registo = forms.DateField()

    class Meta:
            model = Users
            fields = '__all__'

class LoginForm(forms.Form):
    username = forms.CharField(max_length=45)
    password = forms.CharField(max_length=45)

auctionsonline/website/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from django.db import connection
from django.db.models import Q
from django.utils import timezone
from datetime import datetime, time, date
from itertools import chain

from website.forms import *
from website.models import Licitacoes, Leiloes, Produtos, Users, Leiloes, Lotes, Fotos, Negociacoes, Watchlist

from website.validation import validate_login, validate_registration
from website.transactions import increase_bid, remaining_time

from pymongo import MongoClient
conexaomongo = MongoClient("mongodb+srv://Areias:hu58lz@cluster0.kopdoil.mongodb.net/")

db = conexaomongo["BD2Leilao"]


def leilao_list():
    
    dbpsql = connection
    cursor = dbpsql.cursor()

    leiloes = cursor.execute("SELECT * FROM website_leiloes")
    return leiloes

def index(request):
    """
    The main page of the website

    Returns
    -------
    HTTPResponse
        The index page with the current and future Leiloes.
    """
    leiloes = Leiloes.objects.filter(data_hora_fim__gte=datetime.now()).order_by('data_hora_inicio')

    session = request.session.get('session_key')
    if session:
        try:
            user = Users.objects.get(username=session)

            w = Watchlist.objects.filter(username=user)
            watchlist = Leiloes.objects.none()
            for item in w:
                l = Leiloes.objects.filter(leilao_id=item.leiloes)
                negoc  = Negociacoes.objects.filter(negociacoes_id = item.negociacoes)
                watchlist = list(chain(watchlist, l))
                watchlist = list(chain(watchlist, negoc))

            return render(request, 'index.html',
                {'leiloes': leiloes, 'balance': user.credito, 'watchlist': watchlist})
        except Users.DoesNotExist:
            pass

    return render(request, 'index.html', {'leiloes': leiloes})

def bid_page(request, leilao_id):
    """
    Returns the bid page for the
    selected Leiloes.

    Parametes
    ---------
    Leiloe_id : class 'int'

    Returns
    -------
    HTTPResponse
        Return the bidding page for the selected Leiloes.
    Function : index(request)
        If the user is not logged in.
    """
    print(type(leilao_id))
    try:
        # if not logged in return to the index page.
        if request.session['session_key']:
            # If the Leiloes hasn't started return to the index page.
            leilao = Leiloes.objects.filter(id=leilao_id)
            if leilao[0].data_hora_inicio > datetime.now():
                return index(request)
            user = Users.objects.filter(user_id=request.session['session_key'])

            stats = []
            time_left, expired = remaining_time(leilao[0])
            stats.append(time_left) # First element in stats list

            current_cost = 0.20 + (leilao[0].numero_de_licitacoes * 0.20)
            current_cost = "%0.2f" % current_cost
            stats.append(current_cost)

            # Second element in stats list
            if expired < 0: # if Leiloes ended append false.
                stats.append(False)
            else:
                stats.append(True)

            # Third element in stats list
            latest_bid = Licitacoes.objects.all().order_by('-hora_licitacao')
            if latest_bid:
                winner = Users.objects.filter(id=latest_bid[0].user)
                stats.append(winner[0].username)
            else:
                stats.append(None)

            # Getting user's watchlist.
            w = Watchlist.objects.filter(user_id=user[0])
            watchlist = Leiloes.objects.none()
            for item in w:
                l = Leiloes.objects.filter(id=item.leilao_id)
                watchlist = list(chain(watchlist, l))

            return render(request, 'bid.html',
            {
                'Leiloes': leilao[0],
                'user': user[0],
                'stats': stats,
                'watchlist':watchlist
            })
    except KeyError:
        return index(request)

    return index(request)


def raise_bid(request, leilao_id):
    """
    Ver views
    """
    db_connection = connection
    
    leilao = Leiloes.objects.get(id=Leiloes.leilao_id)
    if leilao.hora_fim < timezone.now():
        return bid_page(request, leilao_id)
    elif leilao.data_hora_inicio > datetime.now():
        return index(request)

    try:
        if request.session['session_key']:
            user = Users.objects.get(user_id=request.session['session_key'])
            if user.credito > 0.0:
                latest_bid = Licitacoes.objects.filter(Leilao_id=leilao_id).order_by('-hora_licitacao')
                if not latest_bid:
                    increase_bid(user, leilao_id)
                else:
                    current_winner = Users.objects.filter(id=latest_bid[0].user)
                    if current_winner[0].user_id != user:
                        increase_bid(user, leilao_id)

            return bid_page(request, leilao_id)
    except KeyError:
        return index(request)

    return bid_page(request, leilao_id)

def register_page(request):
    """
    Returns the registration page.

    Returns
    -------
    HTTPResponse
        The registration page.
    """
    return render(request, 'register.html')

def watchlist(request, leilao_id):
    """
    Adds the Leiloes to the user's watchlist.

    Returns
    -------
    Function : index(request)
    """
    try:
        if request.session['session_key']:
            user = Users.objects.filter(user_id=request.session['session_key'])
            leilao = Leiloes.objects.filter(leilao_id=leilao_id)

            w = Watchlist.objects.filter(Leiloe_id=leilao_id)
            if not w:
                watchlist_item = Watchlist()
                watchlist_item.leilao_id = leilao[0]
                watchlist_item.user_id = user[0]
                watchlist_item.save()
            else:
                w.delete()

            return index(request)
    except KeyError:
        return index(request)

    return index(request)

def watchlist_page(request):
    """
    Disguises the index page to look
    like a page with the Leiloes the
    user is watching.

    Returns
    -------
    HTTPResponse
        The index page with Leiloes the user is watching.
    Function : index(request)
        If the user is not logged in.
    """
    try:
        if request.session['session_key']:
            user = Users.objects.filter(username=request.session['session_key'])
            w = Watchlist.objects.filter(user_id=user[0])

            leilao = Leiloes.objects.none()
            for item in w:
                l = leilao.filter(id=item.leilao_id, hora_fim__gte=timezone.now())
                leilao = list(chain(Leiloes, l))
            return render(request, 'index.html', {
                'Leiloes': leilao,
                'user': user[0],
                'watchlist': w
            })
    except KeyError:
        return index(request)

def balance(request):
    """
    If the user is logged in returns
    a HTTPResponse with the page that
    allows the user to update his or her balance.

    Returns
    -------
    HTTPResponse
        The page with the user information
        that updates the account's balance.
    Function : index(request)
        If the user is not logged in.
    """
    try:
        if request.session['username']:
            user = User.objects.filter(username=request.session['username'])
            return render(request, 'balance.html', {'user': user[0]})
    except KeyError:
        return index(request)

    return index(request)

def topup(request):
    """
    Adds credit to user's current balance.

    Returns
    -------
    Function : index(request)
        If the user is not logged in.
    """
    if request.method == 'POST':
        form = TopUpForm(request.POST)
        if form.is_valid():
            try:
                if request.session['username']:
                    user = User.objects.get(username=request.session['username'])
                    userDetails = Users.objects.get(user_id=user.id)
                    userDetails.balance += form.cleaned_data['amount']
                    userDetails.save()
            except KeyError:
                return index(request)

    return index(request)

def filter_leilao(request, categoria):
    """
    Searches current and future Leiloes
    that belong in a categoria.

    Parameters
    ----------
    categoria : class 'str'
        The categoria name.

    Returns
    -------
    Function : index(request)
         If the user is not logged in.
    """
    f_leilao = []
    if categoria == "laptops":
        f_leilao = Leiloes.objects.filter(
            hora_fim__gte=datetime.now(), produto_id__categoria="LAP"
            ).order_by('hora_inicio')

    elif categoria == "consoles":
        f_leilao = Leiloes.objects.filter(
            hora_fim__gte=datetime.now(), produto_id__categoria="CON"
            ).order_by('hora_inicio')

    elif categoria == "games":
        f_leilao = Leiloes.objects.filter(
            hora_fim__gte=datetime.now(), produto_id__categoria="GAM"
            ).order_by('hora_inicio')

    elif categoria == "gadgets":
        f_leilao = Leiloes.objects.filter(
            hora_fim__gte=datetime.now(), produto_id__categoria="GAD"
            ).order_by('hora_inicio')

    elif categoria == "tvs":
        f_leilao = Leiloes.objects.filter(
            hora_fim__gte=datetime.now(), produto_id__categoria="TEL"
            ).order_by('hora_inicio')

    try:
        if request.session["session_key"]:
            leilao = Leiloes.objects.filter(hora_fim__gte=datetime.now()).order_by('hora_inicio')
            user = Users.objects.filter(username=request.session)

            w = Watchlist.objects.filter(user_id=user[0])
            watchlist = Leiloes.objects.none()
            for item in w:

auctionsonline/website/templates/balance.html
<!DOCTYPE html>
<html>
<head>
    <title>Auctions Online - Balance Page</title>
    <style>
        #subbut { margin-top: -15px; }
        #upba { margin-top: 70px; }
        #topupform {margin-bottom: 300px; }
    </style>
</head>
<body>
{% extends 'index.html' %}
{% block body %}
    <div id="upba">
        <h2>Update your Balance</h2>
        <hr>
    </div>
    
    <form id="topupform" method="post" action="/website/balance/topup/">{% csrf_token %}
        <div class="form-group">
            <label for="sel1">Select an amount to top-up your balance:</label>
            <select class="form-control" id="sel1" name="amount">
                <option value="10.00">10€</option>
                <option value="20.00">20€</option>
                <option value="50.00">50€</option>
            </select>
            <br>
        </div>
        <button id="subbut" type="submit" class="btn btn-primary col-sm-12" value="topup">Top Up</button>
    </form>
{% endblock %}
</body>
</html>

auctionsonline/website/templates/bid.html
<!DOCTYPE html>
<html>
<head>
    <title>Auctions Online - Item</title>
    <link rel="stylesheet" type="text/css" href="/static/css/bid.css">
</head>
<body>
{% extends 'index.html' %}
{% block body %}
<div id="bid-flexbox" class="d-flex flex-row">
    <div class="p-2"><img id="preview_product" src="/media/{{ leilao.product_id.image }}" /></div>
    <div class="p-2">

        <div id="bidding" class="jumbotron">
			<div id="bid_table">
            <table  class="table table-borderless">
                <tbody>
                    <tr>
                        {% if stats.2 %}
                        <td><small>Tempo Restante:</small></td>
                        <td>{{ stats.0 }}</td>
                        {% else %}
                        <p>Leilao Acabou! O vencedor é: {{ stats.3 }}</p>
                        {% endif %}
                    </tr>
                    <tr>
                        <td><small>Current bit:</small></td>
                        <td><b>EU {{stats.1}}€</b></td>
                        <td><small>[ {{ Leiloes.numero_de_licitacoes}} Licitações ]</small></td>
                    </tr>
                </tbody>
            </table>
			</div>
			{% if stats.2 %}
            <div>
                <button type="button" id="b_button" class="btn btn-primary" onclick="location.href='/website/bid/{{Leiloes.leilao_id}}/raise_bid'">Bid</button>
            </div>
            {% endif %}
            <div>
                <button type="button" id="w_button" class="btn btn-outline-primary watch_button" onclick="location.href='/website/watchlist/{{Leiloes.leilao_id}}'">
                    {% load custom_tags %}
                    {% if watchlist %}
                        {% if watchlist|search:Leiloes.leilao_id%}
                            Unwatch
                        {% else %}
                            Watch
                        {% endif %}
                    {% else %}
                        Watch
                    {% endif %}
                </button>
            </div>
        </div>

        <div id="comments">
            {% for c in stats.4 %}
            {{ c.user_id.username }} : {{ c.message }}<br>
            {% endfor %}
        </div>

        <form method="post" action="/website/bid/{{Leiloes.leilao_id}}/comment/">{% csrf_token %}
        <div class="form-group">
            <label for="comment">Comentarios:</label>
            <textarea class="form-control" rows="2" id="comment" name="comment"></textarea>
        </div>

        <button id="post_button" type="submit" class="btn btn-outline-primary">Comentar</button>
        </form>
    </div>
</div>
{% endblock %}
</body>
</html>

auctionsonline/website/templates/home.html
<!DOCTYPE html>
<html>
<head>
    <title>Auctions Online</title>
</head>
<body>
    <li class="nav-item open-modal">
        <a class="nav-link" href="/website/balance/">Saldo : €{{ balance }}</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="/website/watchlist/">Leiloes Desejados</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="/website/logout/">Logout</a>
    </li>
</body>
</html>

auctionsonline/website/templates/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Auctions Online</title>

    <!-- Bootstrap 4.0.0 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>

    <!-- Footer related -->
    <link rel="stylesheet" href="/static/css/footer.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

	<!-- MODAL related - Login -->
	<link rel="stylesheet" type="text/css" href="/static/css/modal.css">
	<!-- <link href="https://fonts.googleapis.com/css?family=Barlow+Semi+Condensed" rel="stylesheet"> -->

    <!-- ICON -->
    <link rel="icon" href="/static/images/icon.png">

    <!-- PAGE CSS -->
    <link rel="stylesheet" type="text/css" href="/static/css/index.css">    
    
</head>

<body>

	<!-- Logo -->
	<a href="{% url 'website:index' %}"><img src="/static/images/logosite.png" class="logosite" /></a>
	
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a id="homebutton" class="navbar-brand" href="{% url 'website:index' %}"><img src="/static/images/home.png" class="logo" /></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <ul class="nav nav-pills">
            <li class="nav-item">
                <a class="nav-link" href="/website/Leiloes/">Leiloes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/website/Negociações/">Negociações</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/website/SobreNos/">Sobre Nos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/website/Contactos/">Contactos</a>
            </li>
        </ul>
        
        <ul id="right_navbar" class="navbar-nav ml-auto">
            {% if request.session.user_id %}
                {% include "home.html" %}
            {% else %}
                <li class="nav-item open-modal">
                    <a id="login" href="#myModal" class="nav-link trigger-btn" data-toggle="modal">Login</a>
                </li>
                <li class="nav-item">
                    <a id="signup" class="nav-link" href="/website/register/">Sign up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/website/watchlist/">Leiloes Desejados</a>
                </li>
            {% endif %}
        </ul>
    </nav>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <form class="form-inline mx-auto" action="{% url 'website:search_leiloes' %}">
            <input class="form-control mr-sm-2" name="date" type="date">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit" class="btn-search">Search</button>
        </form>
        </div>
    </nav>
	<!-- Ad and replacement -->
    <div class="d-flex justify-content-center">
        
        <div class="p-2">
            <div id="replacement">
                {% block body%}
				{% include "leiloes.html" %}
                {% endblock %}
            </div>
            
        </div>
    </div>

     <footer class="footer-distributed">
        <div class="footer-left">
            <h3>Auctions<span>online</span></h3>
            <p class="footer-company-name">Auctions Online &copy; 2023</p>
        </div>
    </footer>   
	
	<!-- Login MODAL -->
	<div id="myModal" class="modal fade text-center">
        <div class="modal-dialog">
            <div class="col-lg-8 col-sm-8 col-12 main-section">
                <div class="modal-content">
                    <div class="col-lg-12 col-sm-12 col-12 user-img">
                        <img src="/static/images/man.png">
                    </div>
                    <div class="col-lg-12 col-sm-12 col-12 user-name">
                        <h1>User Login</h1>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="col-lg-12 col-sm-12 col-12 form-input">
                        <form method="POST" action="/website/login/">{% csrf_token %}
                            <div class="form-group">
                                <input name="username" type="text" class="form-control" placeholder="Enter username">
                            </div>
                            <div class="form-group">
                                <input name="password" type="password" class="form-control" placeholder="Password">
                            </div>
                            <button type="submit" class="btn btn-primary">Login</button>
                        </form>
                    </div>
                    <div class="col-lg-12 col-sm-12 col-12 link-part">
                        <a href="http://www.nicesnippets.com" target="_blank">Forgot Password?</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

auctionsonline/website/templates/leiloes.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="/static/css/produtos.css">
</head>
<body>
    <div class="grid-container">
        <!-- Loop through leilaosand create cards -->
        {% for leilao in Leiloes %}
        <div class="card">
            <img class="card-img-top" src='/media/{{ leilao.produto_id.imagem }}' alt="Card image cap">
            <div class="card-body">
                <h4 class="card-title">{{ leilao.produto_id.titulo }}</h4>
                <p class="card-text">{{ leilao.produto_id.descricao }}</p>
                <p class="card-text">Preço Base: {{ leilao.preco_base }}€</p>
                <p class="text-muted">Leilao começa: {{ leilao.hora_inicio|time:'H:i' }}</p>
                <p class="text-muted">Leilao acaba: {{ leilao.hora_fim|time:'H:i' }}</p>
                <!-- BID NOW BUTTON -->
                <button type="button" class="btn btn-primary bid_now_button" onclick="location.href='/website/bid/{{ leilao.leilao_id }}'">Licitar</button>
                <!-- WATCH BUTTON -->
                <button type="button" class="btn btn-outline-primary watch_button" onclick="location.href='/website/watchlist/{{ leilao.id }}'">
                    {% if watchlist %}
                        {% if leilao.leilao_id in watchlist %}
                            Unwatch
                        {% else %}
                            Watch
                        {% endif %}
                    {% else %}
                        Watch
                    {% endif %}
                </button>
            </div>
        </div>
        {% endfor %}
    </div>
</body>
</html>

auctionsonline/website/templates/products.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="/static/css/produtos.css">
</head>
<body>
    <div class="grid-container">
        <!-- Loop through leilaosand create cards -->
        {% for leilao in Leiloes %}
        <div class="card">
            <img class="card-img-top" src='/media/{{ leilao.produto_id.imagem }}' alt="Card image cap">
            <div class="card-body">
                <h4 class="card-title">{{ leilao.produto_id.titulo }}</h4>
                <p class="card-text">{{ leilao.produto_id.descricao }}</p>
                <p class="card-text">Preço Base: {{ leilao.preco_base }}€</p>
                <p class="text-muted">Leilao começa: {{ leilao.hora_inicio|time:'H:i' }}</p>
                <p class="text-muted">Leilao acaba: {{ leilao.hora_fim|time:'H:i' }}</p>
                <!-- BID NOW BUTTON -->
                <button type="button" class="btn btn-primary bid_now_button" onclick="location.href='/website/bid/{{ leilao.leilao_id }}'">Licitar</button>
                <!-- WATCH BUTTON -->
                <button type="button" class="btn btn-outline-primary watch_button" onclick="location.href='/website/watchlist/{{ leilao.id }}'">
                    {% if watchlist %}
                        {% if leilao.leilao_id in watchlist %}
                            Unwatch
                        {% else %}
                            Watch
                        {% endif %}
                    {% else %}
                        Watch
                    {% endif %}
                </button>
            </div>
        </div>
        {% endfor %}
    </div>
</body>
</html>

auctionsonline/website/templates/search_results.html
{% extends 'index.html' %}
<!DOCTYPE html>
<html>
<head>
    <title>Search Results</title>
</head>
<body>
    <h1>Search Results</h1>
    <ul>
        {% for leilao in matching_leiloes %}
            <li>
                Leilao ID: {{ leilao.leilao_id }}<br>
                Number of Licitacoes: {{ leilao.numero_de_licitacoes }}<br>
                Preco Base: {{ leilao.preco_base }}<br>
                Dia: {{ leilao.dia }}<br>
                Hora Inicio: {{ leilao.hora_inicio }}<br>
                Hora Fim: {{ leilao.hora_fim }}<br>
                Incremento Minimo: {{ leilao.incremento_minimo }}<br>
                Watchlist ID: {{ leilao.watch_list_id }}<br>
            </li>
        {% endfor %}
    </ul>
</body>
</html>